<#assign dict_yes_no={'0':'否', '1':'是'}>
<#assign dict_driving_type={'1':'C1-小型汽车','2':'C2-小型自动挡汽车','3':'B1-中型客车','4':'B2-大型货车','5':'A1-大型客车','6':'A2-牵引车'}>
<#assign dict_car_color=['白色','黑色','银色','红色','绿色','黄色','蓝色','其它']>
<#assign dict_insurer={'1':'中国平安保险','2':'中国人民财产保险','3':'中国人寿保险','4':'太平洋保险'}>
<#assign dict_selfDriveOrder_status={ '1':'待开始', '2':'执行中', '3':'已取消','4':'待支付', '5':'待评价', '6':'已完成', '7':'已终止', '8':'已报价', '9':'已下订' }>
<#assign dict_company_source={ '1':'会员来源', '2':'司机来源', '3':'车辆来源' }>
<#assign dict_company_status={ '0':'正常', '1':'禁用', '2':'已过期' }>
<#assign dict_user_status={'0':'正常','1':'禁用'}>
<#assign dict_car_status={'1':'正常','2':'停用','3':'维修','4':'保养'}>
<#assign dict_obd_status={'0':'未使用','1':'已使用','2':'损坏','3':'维修','4':'报废'}>
<#assign dict_parking_status={'0':'正常', '1':'停用'}>
<#assign dict_passenger_status={'0':'启用','1':'禁用'}>
<#assign dict_passenger_audit_status={'0':'未申请', '1':'待审核','2':'审核通过','3':'审核未通过'}>
<#assign dict_passenger_bond_status={'0':'未缴纳', '1':'已交纳','2':'余额不足','3':'申请退款中'}>
<#assign dict_passenger_sex={'1':'男','2':'女'}>
<#assign dict_registerCoupon_status={'0':'启用','1':'禁用'}>
<#assign dict_rechargeOrder_status={'0':'未支付','1':'已支付','3':'已撤销'}>
<#assign dict_rechargeOrder_channel={'alipay':'支付宝','yeepay':'易宝','wxpay':'微信','admin':'管理员','epos':'易宝无卡支付'}>
<#assign dict_rechargeOrder_type={'1':'充值','2':'自驾订单支付','3':'违章押金（保证金）','4':'信用卡验证 ','5':'违章支付'}>
<#assign dict_rechargeOrder_source={'1':'微信小程序','2':'微信公众号','3':'安卓','4':'iOS'}>
<#assign dict_chargingPilePoint_status={'0':'正常','1':'维修','2':'已停用'}>
<#assign dict_fundLog_type={'1':'充值','2':'自驾订单支付','3':'违章押金支付', '4':'信用卡验证', '5':'违章支付', '6':'充值送'}>
<#assign dict_bondRefundOrder_status={'0':'新申请','1':'已退款','2':'已撤销','3':'余额不足退款失败'}>
<#assign dict_bondRefundOrder_channel={'1':'微信','2':'支付宝'}>
<#assign dict_member_progress={'1':'已支付预付款','2':'在快乐学车报名缴费','3':'通过学车体检','4':'预约学习科目一','5':'通过科目一考试','6':'科目二学习中','7':'通过科目二考试','8':'科目三学习中','9':'通过科目三考试','10':'预约学习科目四','11':'通过科目四考试','12':'领取驾驶证'}>
<#assign dict_singup_payType={'0':'全款','1':'首付60%','2':'预付款100元'}>
<#assign dict_theory_subjectType={'1':'科目一','4':'科目四'}>
<#assign dict_theory_questionType={'1':'单选题','2':'多选题','3':'判断题'}>
<#assign dict_theory_answerOption={'A':'A','B':'B','C':'C','D':'D'}>
<#assign dict_theory_answerOfJudge={'A':'对','B':'错'}>
<#assign dict_book_status={'0':'已预约','1':'已练习','2':'已评价','3':'已取消未付违约金','4':'已取消'}>
